version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 3000:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: sample

      VIRTUAL_HOST: domainname1.net
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: domainname1.net
      LETSENCRYPT_EMAIL: emailaddress@test.com
      LETSENCRYPT_TEST: "false"
    volumes:
      - /srv/docker/redmine/redmine:/home/redmine/data
    networks:
      - default
      - ssl_proxy


  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_DATABASE: redmine
    volumes:
      - /srv/docker/redmine/mysql:/var/lib/mysql

networks:
  ssl_proxy:
    external: true
